# Generated by Django 4.2.3 on 2023-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botcommand",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
